"""Shared helpers: every fetcher returns a list of normalized signals.
Signal shape: {source, date, title, url, geography, note}
"""
import json, os, datetime

OUT = os.path.join(os.path.dirname(__file__), "..", "site", "signals.js")

def save(signals):
    signals.sort(key=lambda s: s.get("date",""), reverse=True)
    stamp = datetime.date.today().isoformat()
    body = "const SIGNALS_UPDATED = %s;\nconst SIGNALS = %s;\n" % (
        json.dumps(stamp), json.dumps(signals[:200], indent=1))
    with open(OUT, "w") as f:
        f.write("// Auto-generated by fetchers — do not edit by hand.\n" + body)
    print(f"wrote {len(signals)} signals -> signals.js")
